# Generated by Django 4.2.4 on 2024-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_code',
        ),
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.CharField(default='SEO', max_length=30),
            preserve_default=False,
        ),
    ]
